name: Build Packages

on:
  workflow_dispatch:
  repository_dispatch:
    types: [build]

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.tag }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        tag:
          - openwrt-23.05

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run update.sh in second-level directory
        run: 
          bash xray-core/update.sh

      - name: Build Packages
        uses: pmkol/openwrt-gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.tag }}
          FEEDNAME: packages_ci
          PACKAGES: xray-core
          SET_GOAMD64: v3
          NO_REFRESH_CHECK: true
          IGNORE_ERRORS: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.tag }}-${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk

      - name: Get Latest Tag
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/XTLS/Xray-core/releases/latest | jq -r '.tag_name')
          echo "latest_tag=$RELEASE_COMMITS" >> $GITHUB_ENV
          echo "https://github.com/XTLS/Xray-core/commit/$LATEST_TAG"

      - name: Delete current release assets
        uses: andreaswilli/delete-release-assets-action@v3.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{env.latest_tag}}
          deleteOnlyFromDrafts: false

      - name: Create and Upload Release
        id: upload_release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: ${{env.latest_tag}}
          tag: ${{env.latest_tag}}
          body: Powered by OpenWrt SDK 23.05
          file_glob: true
          overwrite: true
          file: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk
