name: Build Packages

on:
  workflow_dispatch:
  repository_dispatch:
    types: [build]

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.tag }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_generic
          - x86_64
        tag:
          - openwrt-23.05

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Packages
        run: 
          bash xray-core/update.sh

      - name: Build Packages
        uses: pmkol/openwrt-gh-action-sdk@amd64v2
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.tag }}
          FEEDNAME: packages_ci
          PACKAGES: xray-core
          NO_REFRESH_CHECK: true
          IGNORE_ERRORS: true

      - name: Extract package info
        run: |
          for pkg in bin/packages/${{ matrix.arch }}/packages_ci/*.ipk; do
            pkg_name=$(basename "$pkg" | cut -d "_" -f 1)
            pkg_version=$(basename "$pkg" | cut -d "_" -f 2)
            echo "${pkg_name} ${pkg_version}" >> bin/packages/${{ matrix.arch }}/packages_ci/package.ver
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.tag }}-${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk

      - name: Get Latest Tag
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/XTLS/Xray-core/releases/latest | jq -r '.tag_name')
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_ENV
          echo "https://github.com/XTLS/Xray-core/releases/tag/$LATEST_TAG"

      - name: Create and Upload Release
        id: upload_release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: ${{env.latest_tag}}
          tag: ${{env.latest_tag}}
          body: |
            Build OpenWrt packages from xray-core releases:
            https://github.com/XTLS/Xray-core/releases/tag/${{env.latest_tag}}
          file_glob: true
          overwrite: true
          file: bin/packages/${{ matrix.arch }}/packages_ci/*.{ipk,ver}
