name: Build Packages

on:
  workflow_dispatch:
  repository_dispatch:
    types: [build]

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.tag }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_generic
          - x86_64
        tag:
          - openwrt-23.05

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Packages
        run: 
          bash pkg-update.sh

      - name: Build Packages
        uses: pmkol/openwrt-gh-action-sdk@amd64v2
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.tag }}
          FEEDNAME: packages_ci
          PACKAGES: xray-core sing-box
          NO_REFRESH_CHECK: true
          IGNORE_ERRORS: true

      - name: Extract Packages Version
        run: |
          for pkg in bin/packages/${{ matrix.arch }}/packages_ci/*.ipk; do
            pkg_name=$(basename "$pkg" | cut -d "_" -f 1)
            pkg_version=$(basename "$pkg" | cut -d "_" -f 2)
            echo "${pkg_name} ${pkg_version}" >> bin/packages/${{ matrix.arch }}/packages_ci/package.ver
          done
          echo "latest_body=$(cat bin/packages/${{ matrix.arch }}/packages_ci/package.ver)" >> $GITHUB_ENV

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.tag }}-${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk

      - name: Create and Upload Release
        id: upload_release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: OpenWrt-Packages
          tag: latest
          body: ${{env.latest_body}}
          file_glob: true
          overwrite: true
          file: bin/packages/${{ matrix.arch }}/packages_ci/*.{ipk,ver}
