name: Build Packages

on:
  workflow_dispatch:
  repository_dispatch:
    types: [build]

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.tag }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_generic
          - x86_64
        tag:
          - openwrt-23.05

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Packages
        run: 
          bash pkg-update.sh

      - name: Build Packages
        uses: pmkol/openwrt-gh-action-sdk@amd64v2
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.tag }}
          FEEDNAME: packages_ci
          PACKAGES: xray-core sing-box v2ray-geodata
          NO_REFRESH_CHECK: true
          IGNORE_ERRORS: true

      - name: Extract Packages Version
        run: |
          for pkg in bin/packages/${{ matrix.arch }}/packages_ci/*.ipk; do
            pkg_name=$(basename "$pkg" | cut -d "_" -f 1)
            pkg_version=$(basename "$pkg" | cut -d "_" -f 2)
            echo "${pkg_name} ${pkg_version}" >> bin/packages/${{ matrix.arch }}/packages_ci/package.ver
          done
          echo "latest_release=$(date +'%Y%m%d')" >> $GITHUB_ENV
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-${{ matrix.tag }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.{ipk,ver}

  gather-artifacts:
    name: Gather Artifacts
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download aarch64_generic artifacts
        uses: actions/download-artifact@v4
        with:
          name: aarch64_generic-openwrt-23.05
          path: aarch64_generic

      - name: Download x86_64 artifacts
        uses: actions/download-artifact@v4
        with:
          name: x86_64-openwrt-23.05
          path: x86_64

      - name: Combine artifacts
        run: |
          mkdir -p combined
          cp aarch64_generic/* combined/
          cp x86_64/* combined/
      
      - name: Upload combined artifacts
        uses: actions/upload-artifact@v4
        with:
          name: combined-packages
          path: combined/*

  release:
    name: Create and Upload Release
    needs: gather-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Download combined artifacts
        uses: actions/download-artifact@v4
        with:
          name: combined-packages
          path: combined

      - name: Delete current release assets
        uses: andreaswilli/delete-release-assets-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          deleteOnlyFromDrafts: false

      - name: Create and Upload Release
        id: upload_release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: OpenWrt-Packages
          tag: latest
          body: Latest build on ${{ env.latest_release }}
          file_glob: true
          overwrite: true
          file: combined/*.{ipk,ver}
